# Generated by Django 2.1.3 on 2018-11-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20181115_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Volunteer',
        ),
    ]
